"""first commit

Revision ID: b0ae63b50abd
Revises: 
Create Date: 2021-08-30 11:30:46.410202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0ae63b50abd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_role_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户id'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色id'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='用户角色关联表'
    )
    op.create_index(op.f('ix_sys_role_user_id'), 'sys_role_user', ['id'], unique=False)
    op.add_column('sys_role', sa.Column('name', sa.VARCHAR(length=32), nullable=True, comment='角色名'))
    op.drop_column('sys_role', 'role_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_role', sa.Column('role_name', mysql.VARCHAR(length=32), nullable=True, comment='角色名'))
    op.drop_column('sys_role', 'name')
    op.drop_index(op.f('ix_sys_role_user_id'), table_name='sys_role_user')
    op.drop_table('sys_role_user')
    # ### end Alembic commands ###
