"""first commit

Revision ID: be2b85922d31
Revises: b0ae63b50abd
Create Date: 2021-08-30 13:22:56.280202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2b85922d31'
down_revision = 'b0ae63b50abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sys_role_user_ibfk_2', 'sys_role_user', type_='foreignkey')
    op.drop_constraint('sys_role_user_ibfk_1', 'sys_role_user', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('sys_role_user_ibfk_1', 'sys_role_user', 'sys_role', ['role_id'], ['id'])
    op.create_foreign_key('sys_role_user_ibfk_2', 'sys_role_user', 'sys_user', ['user_id'], ['id'])
    # ### end Alembic commands ###
